from setuptools import setup, find_packages

setup(
    name="addrx",
    version="0.1.2",
    author="Joydeep Ghatak",
    author_email="joydeep.ghatak007@gmail.com",
    description="A Python client for parsing address using Libpostal API service.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/joydeep-ghatak/AddrX",
    license="MIT",
    packages=find_packages(),
    install_requires=[
        "annotated-types",
        "anyio",
        "certifi",
        "charset-normalizer",
        "h11",
        "httpcore",
        "httpx",
        "idna",
        "pydantic",
        "pydantic_core",
        "requests",
        "sniffio",
        "typing_extensions",
        "urllib3",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.11',
)
