from setuptools import setup, find_packages

setup(
    name="addrx",
    version="0.1.0",
    author="Joydeep Ghatak",
    author_email="joydeep.ghatak007@gmail.com",
    description="A Python client for parsing address using Libpostal API service.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/joydeep-ghatak/AddrX",
    packages=find_packages(),
    install_requires=[
        "annotated-types==0.7.0",
        "anyio==4.8.0",
        "certifi==2025.1.31",
        "charset-normalizer==3.4.1",
        "h11==0.14.0",
        "httpcore==1.0.7",
        "httpx==0.28.1",
        "idna==3.10",
        "pydantic==2.10.6",
        "pydantic_core==2.27.2",
        "requests==2.32.3",
        "sniffio==1.3.1",
        "typing_extensions==4.12.2",
        "urllib3==2.3.0",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.11',
)
